import Problem from "../models/Problem.js";
import dbConnection from "../config/db.js";
import dotenv from 'dotenv'

dotenv.config();

const problems = [
    {
        problemNumber: 1,
        title: "Two Sum",
        slug: "two-sum",
        difficulty: "Basic",
        tags: ["Array", "HashMap"],
        description: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
        examples: [
            { input: "nums = [2,7,11,15], target = 9", output: "[0,1]", explanation: "nums[0] + nums[1] = 2 + 7 = 9" },
            { input: "nums = [3,2,4], target = 6", output: "[1,2]", explanation: "nums[1] + nums[2] = 2 + 4 = 6" },
        ],
        constraints: ["2 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9", "Only one valid answer exists"],
        testCases: [
            { input: "[2,7,11,15]\n9", expectedOutput: "[0,1]" },
            { input: "[3,2,4]\n6", expectedOutput: "[1,2]" },
            { input: "[3,3]\n6", expectedOutput: "[0,1]" },
            { input: "[1,2,3,4,5]\n9", expectedOutput: "[3,4]" },
            { input: "[0,4,3,0]\n0", expectedOutput: "[0,3]" },
            { input: "[-1,-2,-3,-4,-5]\n-8", expectedOutput: "[2,4]" },
            { input: "[1,5,3,7]\n8", expectedOutput: "[1,3]" },
            { input: "[2,5,5,11]\n10", expectedOutput: "[1,2]" },
            { input: "[1,3,4,2]\n6", expectedOutput: "[2,3]" },
            { input: "[0,1]\n1", expectedOutput: "[0,1]" },
        ],
        starterCode: {
            javascript: `function twoSum(nums, target) {\n  // your code here\n}`,
            python: `def two_sum(nums, target):\n    # your code here\n    pass`,
            cpp: `vector<int> twoSum(vector<int>& nums, int target) {\n    // your code here\n}`,
            java: `public int[] twoSum(int[] nums, int target) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 2,
        title: "Valid Parentheses",
        slug: "valid-parentheses",
        difficulty: "Easy",
        tags: ["Stack", "String"],
        description: 'Given a string s containing just the characters "(", ")", "{", "}", "[" and "]", determine if the input string is valid.',
        examples: [
            { input: 's = "()"', output: "true", explanation: "Opening and closing brackets match" },
            { input: 's = "()[]{}"', output: "true", explanation: "All brackets match in correct order" },
        ],
        constraints: ["1 <= s.length <= 10^4", "s consists of parentheses only '()[]{}'"],
        testCases: [
            { input: "()", expectedOutput: "true" },
            { input: "()[]{}", expectedOutput: "true" },
            { input: "(]", expectedOutput: "false" },
            { input: "([)]", expectedOutput: "false" },
            { input: "{[]}", expectedOutput: "true" },
            { input: "", expectedOutput: "true" },
            { input: "((", expectedOutput: "false" },
            { input: "){", expectedOutput: "false" },
            { input: "({[]})", expectedOutput: "true" },
            { input: "((()))", expectedOutput: "true" },
        ],
        starterCode: {
            javascript: `function isValid(s) {\n  // your code here\n}`,
            python: `def is_valid(s):\n    # your code here\n    pass`,
            cpp: `bool isValid(string s) {\n    // your code here\n}`,
            java: `public boolean isValid(String s) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 3,
        title: "Reverse Linked List",
        slug: "reverse-linked-list",
        difficulty: "Easy",
        tags: ["Linked List"],
        description: "Given the head of a singly linked list, reverse the list, and return the reversed list.",
        examples: [
            { input: "head = [1,2,3,4,5]", output: "[5,4,3,2,1]", explanation: "The list is reversed" },
            { input: "head = [1,2]", output: "[2,1]", explanation: "Two node list reversed" },
        ],
        constraints: ["The number of nodes in the list is in the range [0, 5000]", "-5000 <= Node.val <= 5000"],
        testCases: [
            { input: "[1,2,3,4,5]", expectedOutput: "[5,4,3,2,1]" },
            { input: "[1,2]", expectedOutput: "[2,1]" },
            { input: "[]", expectedOutput: "[]" },
            { input: "[1]", expectedOutput: "[1]" },
            { input: "[1,2,3]", expectedOutput: "[3,2,1]" },
            { input: "[5,4,3,2,1]", expectedOutput: "[1,2,3,4,5]" },
            { input: "[1,1,1]", expectedOutput: "[1,1,1]" },
            { input: "[0,-1]", expectedOutput: "[-1,0]" },
            { input: "[100,200,300]", expectedOutput: "[300,200,100]" },
            { input: "[1,2,3,4]", expectedOutput: "[4,3,2,1]" },
        ],
        starterCode: {
            javascript: `function reverseList(head) {\n  // your code here\n}`,
            python: `def reverse_list(head):\n    # your code here\n    pass`,
            cpp: `ListNode* reverseList(ListNode* head) {\n    // your code here\n}`,
            java: `public ListNode reverseList(ListNode head) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 4,
        title: "Maximum Subarray",
        slug: "maximum-subarray",
        difficulty: "Basic",
        tags: ["Array", "DP"],
        description: "Given an integer array nums, find the subarray with the largest sum, and return its sum.",
        examples: [
            { input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", output: "6", explanation: "Subarray [4,-1,2,1] has the largest sum = 6" },
            { input: "nums = [1]", output: "1", explanation: "Only one element" },
        ],
        constraints: ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
        testCases: [
            { input: "[-2,1,-3,4,-1,2,1,-5,4]", expectedOutput: "6" },
            { input: "[1]", expectedOutput: "1" },
            { input: "[5,4,-1,7,8]", expectedOutput: "23" },
            { input: "[-1,-2,-3]", expectedOutput: "-1" },
            { input: "[0,0,0]", expectedOutput: "0" },
            { input: "[-2,-1]", expectedOutput: "-1" },
            { input: "[1,2,3,4,5]", expectedOutput: "15" },
            { input: "[-1,2,3,-4,5]", expectedOutput: "6" },
            { input: "[4,-1,2,1]", expectedOutput: "6" },
            { input: "[-3,4,-2,2,-1]", expectedOutput: "4" },
        ],
        starterCode: {
            javascript: `function maxSubArray(nums) {\n  // your code here\n}`,
            python: `def max_sub_array(nums):\n    # your code here\n    pass`,
            cpp: `int maxSubArray(vector<int>& nums) {\n    // your code here\n}`,
            java: `public int maxSubArray(int[] nums) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 5,
        title: "Climbing Stairs",
        slug: "climbing-stairs",
        difficulty: "Basic",
        tags: ["DP", "Math"],
        description: "You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
        examples: [
            { input: "n = 2", output: "2", explanation: "1+1 or 2" },
            { input: "n = 3", output: "3", explanation: "1+1+1, 1+2, or 2+1" },
        ],
        constraints: ["1 <= n <= 45"],
        testCases: [
            { input: "1", expectedOutput: "1" },
            { input: "2", expectedOutput: "2" },
            { input: "3", expectedOutput: "3" },
            { input: "4", expectedOutput: "5" },
            { input: "5", expectedOutput: "8" },
            { input: "6", expectedOutput: "13" },
            { input: "10", expectedOutput: "89" },
            { input: "15", expectedOutput: "987" },
            { input: "20", expectedOutput: "10946" },
            { input: "45", expectedOutput: "1836311903" },
        ],
        starterCode: {
            javascript: `function climbStairs(n) {\n  // your code here\n}`,
            python: `def climb_stairs(n):\n    # your code here\n    pass`,
            cpp: `int climbStairs(int n) {\n    // your code here\n}`,
            java: `public int climbStairs(int n) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 6,
        title: "Best Time to Buy and Sell Stock",
        slug: "best-time-stock",
        difficulty: "Basic",
        tags: ["Array", "Greedy"],
        description: "You are given an array prices where prices[i] is the price of a given stock on the ith day. Return the maximum profit you can achieve.",
        examples: [
            { input: "prices = [7,1,5,3,6,4]", output: "5", explanation: "Buy on day 2 (price=1), sell on day 5 (price=6), profit=5" },
            { input: "prices = [7,6,4,3,1]", output: "0", explanation: "No profit possible, return 0" },
        ],
        constraints: ["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^4"],
        testCases: [
            { input: "[7,1,5,3,6,4]", expectedOutput: "5" },
            { input: "[7,6,4,3,1]", expectedOutput: "0" },
            { input: "[1,2]", expectedOutput: "1" },
            { input: "[2,1]", expectedOutput: "0" },
            { input: "[3,3,3]", expectedOutput: "0" },
            { input: "[1,2,3,4,5]", expectedOutput: "4" },
            { input: "[5,4,3,2,1,6]", expectedOutput: "5" },
            { input: "[2,4,1,7]", expectedOutput: "6" },
            { input: "[1]", expectedOutput: "0" },
            { input: "[0,10]", expectedOutput: "10" },
        ],
        starterCode: {
            javascript: `function maxProfit(prices) {\n  // your code here\n}`,
            python: `def max_profit(prices):\n    # your code here\n    pass`,
            cpp: `int maxProfit(vector<int>& prices) {\n    // your code here\n}`,
            java: `public int maxProfit(int[] prices) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 7,
        title: "Longest Substring Without Repeating Characters",
        slug: "longest-substring",
        difficulty: "Medium",
        tags: ["Sliding Window", "String"],
        description: "Given a string s, find the length of the longest substring without repeating characters.",
        examples: [
            { input: 's = "abcabcbb"', output: "3", explanation: 'The answer is "abc" with length 3' },
            { input: 's = "bbbbb"', output: "1", explanation: 'The answer is "b" with length 1' },
        ],
        constraints: ["0 <= s.length <= 5 * 10^4", "s consists of English letters, digits, symbols and spaces"],
        testCases: [
            { input: "abcabcbb", expectedOutput: "3" },
            { input: "bbbbb", expectedOutput: "1" },
            { input: "pwwkew", expectedOutput: "3" },
            { input: "", expectedOutput: "0" },
            { input: "au", expectedOutput: "2" },
            { input: "dvdf", expectedOutput: "3" },
            { input: "abcdef", expectedOutput: "6" },
            { input: "aab", expectedOutput: "2" },
            { input: "tmmzuxt", expectedOutput: "5" },
            { input: "ohvhjdml", expectedOutput: "6" },
        ],
        starterCode: {
            javascript: `function lengthOfLongestSubstring(s) {\n  // your code here\n}`,
            python: `def length_of_longest_substring(s):\n    # your code here\n    pass`,
            cpp: `int lengthOfLongestSubstring(string s) {\n    // your code here\n}`,
            java: `public int lengthOfLongestSubstring(String s) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 8,
        title: "Merge Intervals",
        slug: "merge-intervals",
        difficulty: "Medium",
        tags: ["Array", "Sorting"],
        description: "Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals.",
        examples: [
            { input: "intervals = [[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]", explanation: "[1,3] and [2,6] overlap, merge to [1,6]" },
            { input: "intervals = [[1,4],[4,5]]", output: "[[1,5]]", explanation: "[1,4] and [4,5] are considered overlapping" },
        ],
        constraints: ["1 <= intervals.length <= 10^4", "intervals[i].length == 2", "0 <= starti <= endi <= 10^4"],
        testCases: [
            { input: "[[1,3],[2,6],[8,10],[15,18]]", expectedOutput: "[[1,6],[8,10],[15,18]]" },
            { input: "[[1,4],[4,5]]", expectedOutput: "[[1,5]]" },
            { input: "[[1,4],[2,3]]", expectedOutput: "[[1,4]]" },
            { input: "[[1,2],[3,4]]", expectedOutput: "[[1,2],[3,4]]" },
            { input: "[[1,4],[0,4]]", expectedOutput: "[[0,4]]" },
            { input: "[[1,4],[0,1]]", expectedOutput: "[[0,4]]" },
            { input: "[[2,3],[4,5],[6,7]]", expectedOutput: "[[2,3],[4,5],[6,7]]" },
            { input: "[[1,10],[2,3],[4,5]]", expectedOutput: "[[1,10]]" },
            { input: "[[1,3]]", expectedOutput: "[[1,3]]" },
            { input: "[[1,3],[2,4],[3,5]]", expectedOutput: "[[1,5]]" },
        ],
        starterCode: {
            javascript: `function merge(intervals) {\n  // your code here\n}`,
            python: `def merge(intervals):\n    # your code here\n    pass`,
            cpp: `vector<vector<int>> merge(vector<vector<int>>& intervals) {\n    // your code here\n}`,
            java: `public int[][] merge(int[][] intervals) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 9,
        title: "Binary Tree Level Order Traversal",
        slug: "binary-tree-level-order",
        difficulty: "Medium",
        tags: ["Tree", "BFS"],
        description: "Given the root of a binary tree, return the level order traversal of its nodes' values (i.e., from left to right, level by level).",
        examples: [
            { input: "root = [3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]", explanation: "Level by level traversal" },
            { input: "root = [1]", output: "[[1]]", explanation: "Single node tree" },
        ],
        constraints: ["The number of nodes in the tree is in the range [0, 2000]", "-1000 <= Node.val <= 1000"],
        testCases: [
            { input: "[3,9,20,null,null,15,7]", expectedOutput: "[[3],[9,20],[15,7]]" },
            { input: "[1]", expectedOutput: "[[1]]" },
            { input: "[]", expectedOutput: "[]" },
            { input: "[1,2,3]", expectedOutput: "[[1],[2,3]]" },
            { input: "[1,null,2,null,3]", expectedOutput: "[[1],[2],[3]]" },
            { input: "[1,2,null,3]", expectedOutput: "[[1],[2],[3]]" },
            { input: "[1,2,3,4,5]", expectedOutput: "[[1],[2,3],[4,5]]" },
            { input: "[0]", expectedOutput: "[[0]]" },
            { input: "[1,2,3,null,5]", expectedOutput: "[[1],[2,3],[5]]" },
            { input: "[1,2,3,4,null,null,5]", expectedOutput: "[[1],[2,3],[4,5]]" },
        ],
        starterCode: {
            javascript: `function levelOrder(root) {\n  // your code here\n}`,
            python: `def level_order(root):\n    # your code here\n    pass`,
            cpp: `vector<vector<int>> levelOrder(TreeNode* root) {\n    // your code here\n}`,
            java: `public List<List<Integer>> levelOrder(TreeNode root) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 10,
        title: "Number of Islands",
        slug: "number-of-islands",
        difficulty: "Medium",
        tags: ["BFS", "DFS", "Graph"],
        description: "Given an m x n 2D binary grid which represents a map of '1's (land) and '0's (water), return the number of islands.",
        examples: [
            { input: 'grid = [["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]', output: "1", explanation: "All land is connected forming one island" },
            { input: 'grid = [["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]', output: "3", explanation: "Three separate islands" },
        ],
        constraints: ["m == grid.length", "n == grid[i].length", "1 <= m, n <= 300", "grid[i][j] is '0' or '1'"],
        testCases: [
            { input: '[["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]', expectedOutput: "1" },
            { input: '[["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]', expectedOutput: "3" },
            { input: '[["1"]]', expectedOutput: "1" },
            { input: '[["0"]]', expectedOutput: "0" },
            { input: '[["1","0"],["0","1"]]', expectedOutput: "2" },
            { input: '[["1","1"],["1","1"]]', expectedOutput: "1" },
            { input: '[["0","0"],["0","0"]]', expectedOutput: "0" },
            { input: '[["1","0","1"],["0","1","0"],["1","0","1"]]', expectedOutput: "5" },
            { input: '[["1","1","1"],["0","1","0"],["1","1","1"]]', expectedOutput: "1" },
            { input: '[["1"],["1"],["1"]]', expectedOutput: "1" },
        ],
        starterCode: {
            javascript: `function numIslands(grid) {\n  // your code here\n}`,
            python: `def num_islands(grid):\n    # your code here\n    pass`,
            cpp: `int numIslands(vector<vector<char>>& grid) {\n    // your code here\n}`,
            java: `public int numIslands(char[][] grid) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 11,
        title: "Word Search",
        slug: "word-search",
        difficulty: "Hard",
        tags: ["Backtracking", "DFS"],
        description: "Given an m x n grid of characters board and a string word, return true if word exists in the grid.",
        examples: [
            { input: 'board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCCED"', output: "true", explanation: "The word exists in the grid" },
            { input: 'board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCB"', output: "false", explanation: "Cannot reuse cells" },
        ],
        constraints: ["m == board.length", "n = board[i].length", "1 <= m, n <= 6", "1 <= word.length <= 15"],
        testCases: [
            { input: '[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]]\nABCCED', expectedOutput: "true" },
            { input: '[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]]\nSEE', expectedOutput: "true" },
            { input: '[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]]\nABCB', expectedOutput: "false" },
            { input: '[["a"]]\na', expectedOutput: "true" },
            { input: '[["a"]]\nb', expectedOutput: "false" },
            { input: '[["A","B"],["C","D"]]\nABDC', expectedOutput: "true" },
            { input: '[["A","B"],["C","D"]]\nABCD', expectedOutput: "false" },
            { input: '[["a","b"],["c","d"]]\nacdb', expectedOutput: "true" },
            { input: '[["C","A","A"],["A","A","A"],["B","C","D"]]\nAAB', expectedOutput: "true" },
            { input: '[["A","B","C","E"],["S","F","E","S"],["A","D","E","E"]]\nABCESEEDFSA', expectedOutput: "false" },
        ],
        starterCode: {
            javascript: `function exist(board, word) {\n  // your code here\n}`,
            python: `def exist(board, word):\n    # your code here\n    pass`,
            cpp: `bool exist(vector<vector<char>>& board, string word) {\n    // your code here\n}`,
            java: `public boolean exist(char[][] board, String word) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 12,
        title: "Median of Two Sorted Arrays",
        slug: "median-two-arrays",
        difficulty: "Hard",
        tags: ["Binary Search", "Array"],
        description: "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.",
        examples: [
            { input: "nums1 = [1,3], nums2 = [2]", output: "2.0", explanation: "Merged array = [1,2,3], median = 2" },
            { input: "nums1 = [1,2], nums2 = [3,4]", output: "2.5", explanation: "Merged array = [1,2,3,4], median = (2+3)/2 = 2.5" },
        ],
        constraints: ["nums1.length == m", "nums2.length == n", "0 <= m <= 1000", "0 <= n <= 1000"],
        testCases: [
            { input: "[1,3]\n[2]", expectedOutput: "2.0" },
            { input: "[1,2]\n[3,4]", expectedOutput: "2.5" },
            { input: "[0,0]\n[0,0]", expectedOutput: "0.0" },
            { input: "[]\n[1]", expectedOutput: "1.0" },
            { input: "[2]\n[]", expectedOutput: "2.0" },
            { input: "[1,3]\n[2,4]", expectedOutput: "2.5" },
            { input: "[1,2,3]\n[4,5,6]", expectedOutput: "3.5" },
            { input: "[1]\n[2,3,4,5]", expectedOutput: "3.0" },
            { input: "[1,5]\n[2,3,4]", expectedOutput: "3.0" },
            { input: "[1,2,3,4,5]\n[6,7,8,9,10]", expectedOutput: "5.5" },
        ],
        starterCode: {
            javascript: `function findMedianSortedArrays(nums1, nums2) {\n  // your code here\n}`,
            python: `def find_median_sorted_arrays(nums1, nums2):\n    # your code here\n    pass`,
            cpp: `double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n    // your code here\n}`,
            java: `public double findMedianSortedArrays(int[] nums1, int[] nums2) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 13,
        title: "Contains Duplicate",
        slug: "contains-duplicate",
        difficulty: "Basic",
        tags: ["Array", "HashSet"],
        description: "Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.",
        examples: [
            { input: "nums = [1,2,3,1]", output: "true", explanation: "1 appears twice" },
            { input: "nums = [1,2,3,4]", output: "false", explanation: "All elements are distinct" },
        ],
        constraints: ["1 <= nums.length <= 10^5", "-10^9 <= nums[i] <= 10^9"],
        testCases: [
            { input: "[1,2,3,1]", expectedOutput: "true" },
            { input: "[1,2,3,4]", expectedOutput: "false" },
            { input: "[1,1,1,3,3,4,3,2,4,2]", expectedOutput: "true" },
            { input: "[1]", expectedOutput: "false" },
            { input: "[]", expectedOutput: "false" },
            { input: "[0,0]", expectedOutput: "true" },
            { input: "[-1,-1]", expectedOutput: "true" },
            { input: "[1,2,3,4,5]", expectedOutput: "false" },
            { input: "[5,5,5,5]", expectedOutput: "true" },
            { input: "[1,2,3,4,1]", expectedOutput: "true" },
        ],
        starterCode: {
            javascript: `function containsDuplicate(nums) {\n  // your code here\n}`,
            python: `def contains_duplicate(nums):\n    # your code here\n    pass`,
            cpp: `bool containsDuplicate(vector<int>& nums) {\n    // your code here\n}`,
            java: `public boolean containsDuplicate(int[] nums) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 14,
        title: "Binary Search",
        slug: "binary-search",
        difficulty: "Easy",
        tags: ["Binary Search", "Array"],
        description: "Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, return its index. Otherwise, return -1.",
        examples: [
            { input: "nums = [-1,0,3,5,9,12], target = 9", output: "4", explanation: "9 exists at index 4" },
            { input: "nums = [-1,0,3,5,9,12], target = 2", output: "-1", explanation: "2 does not exist" },
        ],
        constraints: ["1 <= nums.length <= 10^4", "All integers in nums are unique", "nums is sorted in ascending order"],
        testCases: [
            { input: "[-1,0,3,5,9,12]\n9", expectedOutput: "4" },
            { input: "[-1,0,3,5,9,12]\n2", expectedOutput: "-1" },
            { input: "[1]\n1", expectedOutput: "0" },
            { input: "[1]\n2", expectedOutput: "-1" },
            { input: "[1,2,3,4,5]\n3", expectedOutput: "2" },
            { input: "[1,2,3,4,5]\n1", expectedOutput: "0" },
            { input: "[1,2,3,4,5]\n5", expectedOutput: "4" },
            { input: "[-5,-3,-1,0,2,4]\n-3", expectedOutput: "1" },
            { input: "[2,5,8,12,16,23]\n23", expectedOutput: "5" },
            { input: "[1,3,5,7,9,11]\n6", expectedOutput: "-1" },
        ],
        starterCode: {
            javascript: `function search(nums, target) {\n  // your code here\n}`,
            python: `def search(nums, target):\n    # your code here\n    pass`,
            cpp: `int search(vector<int>& nums, int target) {\n    // your code here\n}`,
            java: `public int search(int[] nums, int target) {\n    // your code here\n}`,
        },
    },
    {
        problemNumber: 15,
        title: "Linked List Cycle",
        slug: "linked-list-cycle",
        difficulty: "Easy",
        tags: ["Linked List", "Two Pointers"],
        description: "Given head, the head of a linked list, determine if the linked list has a cycle in it.",
        examples: [
            { input: "head = [3,2,0,-4], pos = 1", output: "true", explanation: "Tail connects to node at index 1" },
            { input: "head = [1,2], pos = 0", output: "true", explanation: "Tail connects to node at index 0" },
        ],
        constraints: ["The number of the nodes in the list is in the range [0, 10^4]", "-10^5 <= Node.val <= 10^5"],
        testCases: [
            { input: "[3,2,0,-4]\n1", expectedOutput: "true" },
            { input: "[1,2]\n0", expectedOutput: "true" },
            { input: "[1]\n-1", expectedOutput: "false" },
            { input: "[1,2,3,4,5]\n2", expectedOutput: "true" },
            { input: "[1,2,3,4,5]\n-1", expectedOutput: "false" },
            { input: "[-1]\n-1", expectedOutput: "false" },
            { input: "[1,2]\n-1", expectedOutput: "false" },
            { input: "[1,2,3]\n0", expectedOutput: "true" },
            { input: "[0,1]\n-1", expectedOutput: "false" },
            { input: "[1,2,3,4]\n3", expectedOutput: "true" },
        ],
        starterCode: {
            javascript: `function hasCycle(head) {\n  // your code here\n}`,
            python: `def has_cycle(head):\n    # your code here\n    pass`,
            cpp: `bool hasCycle(ListNode *head) {\n    // your code here\n}`,
            java: `public boolean hasCycle(ListNode head) {\n    // your code here\n}`,
        },
    },
]

const seed = async () => {

    try {

        //db connect
        await dbConnection();

        //delete existing problemset
        await Problem.deleteMany();
        console.log('deleted the existing problems');


        //insert the problems now
        await Problem.insertMany(problems)
        console.log('problems seeded successfully');

        process.exit(0); // 0 = success, everything went fine

    } catch (err) {
        console.log('error while seeding problems', err.message);
        process.exit(1); // 1 = failure, something went wrong
    }

}
seed();