export const mockProblems = [
    {
        id: 1,
        title: "Two Sum",
        slug: "two-sum",
        difficulty: "Basic",
        tags: ["Array", "HashMap"],
        solved: true,
    },
    {
        id: 2,
        title: "Valid Parentheses",
        slug: "valid-parentheses",
        difficulty: "Easy",
        tags: ["Stack", "String"],
        solved: true,
    },
    {
        id: 3,
        title: "Reverse Linked List",
        slug: "reverse-linked-list",
        difficulty: "Easy",
        tags: ["Linked List"],
        solved: false,
    },
    {
        id: 4,
        title: "Best Time to Buy and Sell Stock",
        slug: "best-time-stock",
        difficulty: "Basic",
        tags: ["Array", "Greedy"],
        solved: false,
    },
    {
        id: 5,
        title: "Longest Substring Without Repeating",
        slug: "longest-substring",
        difficulty: "Medium",
        tags: ["Sliding Window", "String"],
        solved: false,
    },
    {
        id: 6,
        title: "Merge Intervals",
        slug: "merge-intervals",
        difficulty: "Medium",
        tags: ["Array", "Sorting"],
        solved: false,
    },
    {
        id: 7,
        title: "Binary Tree Level Order Traversal",
        slug: "binary-tree-level-order",
        difficulty: "Medium",
        tags: ["Tree", "BFS"],
        solved: false,
    },
    {
        id: 8,
        title: "Maximum Subarray",
        slug: "maximum-subarray",
        difficulty: "Basic",
        tags: ["Array", "DP"],
        solved: true,
    },
    {
        id: 9,
        title: "Word Search",
        slug: "word-search",
        difficulty: "Hard",
        tags: ["Backtracking", "DFS"],
        solved: false,
    },
    {
        id: 10,
        title: "Median of Two Sorted Arrays",
        slug: "median-two-arrays",
        difficulty: "Hard",
        tags: ["Binary Search", "Array"],
        solved: false,
    },
    {
        id: 11,
        title: "Climbing Stairs",
        slug: "climbing-stairs",
        difficulty: "Basic",
        tags: ["DP", "Math"],
        solved: true,
    },
    {
        id: 12,
        title: "Number of Islands",
        slug: "number-of-islands",
        difficulty: "Medium",
        tags: ["BFS", "DFS", "Graph"],
        solved: false,
    },
]